lists/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: "callbacks" }

  root to: 'welcome#home'

  resources :tags

  resources :users, only: [:show]

  resources :lists do

    resources :tasks  
  end

  get '/search', to: 'lists#search'
  post '/search', to: 'lists#search'

  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

lists/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  has_many :task_tags
  has_many :tags, through: :task_tags

  validates_presence_of :name
  validate :date_format

  scope :overdue, -> {
    all.select(&:overdue)
  }

  def date_format
    errors.add(:due_date, "Please format the due date as indicated YYYY-MM-DD") if due_date.nil?
  end

  def tags_attributes=(tag_attributes)
    tag = Tag.find_or_create_by(tag_attributes.values[0]) if tag_attributes.values[0]["name"].match(/[a-zA-Z]/)
    tags << tag if tag and not tags.include?(tag)
  end

  def overdue
    due_date < Time.now
  end

  def format_due_date
    due_date.strftime("%A, %B %e, %Y") + (overdue ? " (OVERDUE)" : "")
  end
end

lists/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @task = Task.new(task_params)
    if not @task.save
      @list = List.find(params[:task][:list_id])
      return render '/lists/show', id: params[:task][:list_id]
    end
    @task.update(status: "Incomplete")

    redirect_to list_path(task_params[:list_id]) 
  end

  def show
    @task = Task.find_by(id: params[:id])
    if @task.nil?
      not_found
    elsif not authorize_resource(current_user,@task,:show)
      return redirect_to lists_path
    end
  end

  def edit
    if params[:list_id]
      list = List.find_by(id: params[:list_id])
      if list.nil?
        flash[:warning] = "List not found."
        return redirect_to lists_path
      elsif not authorize_resource(current_user,list,:show)
        return redirect_to lists_path
      else
        @task = list.tasks.find_by(id: params[:id])
        if @task.nil? 
          flash[:warning] = "Task not found."
          return redirect_to list_path(list)
        end
      end
    else
      @task = task.find(params[:id])
    end
  end

  def update
    @task = Task.find(params[:id])
    return redirect_to lists_path if not authorize_resource(current_user,@task,:update)
    if not @task.update(task_params)
      return render :edit
    end

    redirect_to task_path(@task)
  end

  def destroy
    task = Task.find(params[:id])
    return redirect_to lists_path if not authorize_resource(current_user,task,:destroy)
    list = task.list
    task.destroy

    redirect_to list_path(list)
  end

  private

  def task_params
    params.require(:task).permit(:name,:description,:due_date,:status,:list_id, tag_ids: [], tags_attributes: [:name])
  end
end

lists/app/views/tasks/_form.html.erb
<% if task.errors.any? %>
  <div class="alert alert-warning" id="error_explanation">
    <p>
      <%= pluralize(task.errors.count, "error") %>
      prohibited this task from being saved:
    </p>
 
    <ul>
    <% task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for task do |f| %>
  <%= f.hidden_field :list_id, value: (@list.id if @list) || task.list_id %>
  <p> 
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
  <p>
    <%= f.label "Due (yyyy-mm-dd)" %><br>
    <%= f.text_field :due_date ,value: (task.due_date.strftime("%Y-%m-%d") if task.due_date)%>
  </p>
  <p> 
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </p>
  <br>
  <h5>Task Tags</h5>
  <p>
  <% if Tag.all.empty? %>
    There are no tags defined.
  <% else %>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name, value: true do |elem| %>
      <%= elem.check_box + elem.text %>&nbsp;
    <% end %>
  <% end %>
  </p>
  <p>
    <h6>New Tag:</h6>
    <%= f.fields_for :tags, task.tags.build do |tag_fields| %>
      <%= tag_fields.text_field :name %>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

lists/app/views/tasks/edit.html.erb
<%= render partial: "layouts/single_center_top" %>

  <h3>Edit Task</h3>
  <%= render partial: "form", locals: {task: @task} %>

<%= render partial: "layouts/single_center_bottom" %>

lists/app/views/tasks/show.html.erb
<%= render partial: "layouts/single_center_top" %>

  <p><%= link_to "Back to list", list_path(@task.list) %></p>
  <h3><%= @task.name %></h3>
  <h5><%= @task.description %></h5>
  <p>&nbsp;</p>
  <h6>Due: <%= @task.due_date.strftime("%A, %B %e, %Y") %></h6>
  <h6>Status: <%= @task.status %></h6>

  <p><%= link_to "Edit", edit_list_task_path(@task.list,@task) %></p>
  <p><%= link_to "Delete", list_task_path(@task.list,@task), method: "delete", data: {confirm: "Are you sure?"} %></p>

  <p>&nbsp;</p>
  <h5>Tags</h5>
  <%= @task.tags.map(&:name).join(", ") %>

<%= render partial: "layouts/single_center_bottom" %>