lists/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: "callbacks" }

  root to: 'welcome#home'

  resources :tags

  resources :users, only: [:show]

  resources :lists do

    resources :tasks  
  end

  get '/search', to: 'lists#search'
  post '/search', to: 'lists#search'

  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

lists/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :task_tags
  has_many :tasks, through: :task_tags
end

lists/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find_by(id: params[:id])
    if @tag.nil?
      not_found
    end
  end

  def new
    @tag = Tag.new
  end

  def create
    tag = Tag.find_or_create_by(tag_params)

    redirect_to tag_path(tag)
  end

  def edit
    @tag = Tag.find_by(id: params[:id])
    if @tag.nil?
      not_found
    elsif not authorize_resource(current_user,@tag,:edit)
      return redirect_to lists_path
    end
  end

  def update
    tag = Tag.find(params[:id])
    return redirect_to lists_path if not authorize_resource(current_user,tag,:update)
    tag.update(tag_params)

    redirect_to tag_path(tag)
  end

  def destroy
    tag = Tag.find(params[:id])
    return redirect_to lists_path if not authorize_resource(current_user,tag,:destroy)
    tag.destroy

    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

lists/app/views/tags/_form.html.erb
<%= form_for tag do |f| %>
  <p><%= f.label :name %><br>
  <%= f.text_field :name %><br></p>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

lists/app/views/tags/edit.html.erb
<%= render partial: "layouts/single_center_top" %>

  <h4>Edit Tag</h4>

  <%= render partial: "form", locals: {tag: @tag, create_or_update_text: @create_or_update_text} %>

<%= render partial: "layouts/single_center_bottom" %>

lists/app/views/tags/index.html.erb
<%= render partial: "layouts/single_center_top" %>
  
  <h3>Tags</h3>
  
  <p>&nbsp;</p>
  
  <% @tags.each do |tag| %>
    <h5><%= link_to tag.name, tag_path(tag) %></h5>
  <% end %>

  <p>&nbsp;</p>
  <%= link_to "New Tag", new_tag_path %>

<%= render partial: "layouts/single_center_bottom" %>

lists/app/views/tags/new.html.erb
<%= render partial: "layouts/single_center_top" %>

  <h4>Create Tag</h4>

  <%= render partial: "form", locals: {tag: @tag, create_or_update_text: @create_or_update_text} %>

<%= render partial: "layouts/single_center_bottom" %>

lists/app/views/tags/show.html.erb
<%= render partial: "layouts/single_center_top" %>

  <h4><%= @tag.name %></h4>
    <p><%= link_to "Edit", edit_tag_path(@tag) if authorize_resource(current_user,@tag,:edit) %></p>

    <p><%= link_to "Delete", tag_path(@tag), method: "delete", data: {confirm: "Are you sure?"} if authorize_resource(current_user,@tag,:destroy) %></p>

    <p>&nbsp;</p>
    <%= link_to "Back to tag list", tags_path %>

<%= render partial: "layouts/single_center_bottom" %>