lists/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: "callbacks" }

  root to: 'welcome#home'

  resources :tags

  resources :users, only: [:show]

  resources :lists do

    resources :tasks  
  end

  get '/search', to: 'lists#search'
  post '/search', to: 'lists#search'

  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

lists/app/models/list.rb
class List < ApplicationRecord
  has_many :user_lists
  has_many :users, through: :user_lists
  has_many :tasks

  validates :name, presence: true

  def update_permission(user,permission)
    user_lists.where(user_id: user.id).first.update(permission: permission)
  end

  def permission(user)
    user_lists.where(user_id: user.id).first.permission
  end

  def collaborators=(emails)
    collaborator_list = emails.gsub(","," ").split(/\s+/).map{|email| User.find_by(email: email)}.compact
    creator = user_lists.where(permission: "creator").first.user 
    collaborator_list << creator
    self.users.clear
    collaborator_list.uniq.each do |u| 
      self.users << u
      update_permission(u, "collaborator")
    end
    update_permission(creator, "creator")
    save
  end

  def collaborators(include_creator=false)
    users.map{|user| if permission(user) == "creator" then (include_creator ? user.email + " (creator)" : "") else user.email end}.join(", ")
  end

  def self.search(query, list_id, user_id)
    anchor = User.find_by(id: user_id)
    
    anchor = anchor.lists.find_by(id: list_id) if list_id.match(/\S/)
    return {error: "List #{list_id} was not found."} if anchor.nil? 

    anchor.tasks.joins(:tags).where("tasks.name LIKE '%#{query}%' OR tasks.description LIKE '%#{query}%' OR tags.name LIKE '%#{query}%'").distinct
  end
end

lists/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find_by(id: params[:id])
    if @list.nil?
      not_found
    elsif !authorize_resource(current_user,@list,:show)
      return redirect_to lists_path
    end
    @task = Task.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(name: list_params[:name])
    if not @list.save
      return render :new
    end
    @list.users << current_user
    @list.update_permission(current_user,"creator")
    @list.collaborators = list_params[:collaborators]

    redirect_to list_path(@list)
  end

  def edit
    @list = List.find_by(id: params[:id])
    if @list.nil?
      not_found
    elsif !authorize_resource(current_user,@list,:edit)
      return redirect_to lists_path
    end
  end

  def update
    @list = List.find(params[:id])
    return redirect_to lists_path if !authorize_resource(current_user,@list,:update)
    if not @list.update(list_params)
      return render :edit 
    end
    redirect_to list_path(@list)
  end

  def destroy
    list = List.find_by(id: params[:id])
    return redirect_to lists_path if not authorize_resource(current_user,list,:destroy)
    list.tasks.map(&:destroy)
    list.destroy

    redirect_to lists_path
  end

  def search
    if params[:search]
      @results = List.search(search_params["query"],search_params["list_id"],current_user.id)
      @query = search_params.to_h
    end
  end

  private

  def list_params
    params.require(:list).permit(:name,:collaborators)
  end

  def search_params
    params.require(:search).permit(:query,:list_id)
  end
end

lists/app/helpers/lists_helper.rb
module ListsHelper
  def format_search_query_text(query_hash)
    str = "You searched for: \"#{query_hash["query"]}\" in " 
    str += query_hash["list_id"].match(/\S/) ? "list #{query_hash["list_id"]}" : "all your lists"
    str + "."
  end
end

lists/app/views/lists/_form.html.erb
<% if list.errors.any? %>
  <div class="alert alert-warning" id="error_explanation">
    <p>
      <%= pluralize(list.errors.count, "error") %>
      prohibited this list from being saved:
    </p>
 
    <ul>
    <% list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for list do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </p>
  <p>
    <%= f.label "collaborators", "Collaborators (add emails separated by commas or spaces)"%><br>
    <%= f.text_area "collaborators", value: list.collaborators %> 
  </p>

  <%= f.submit class: "btn btn-primary"%>
<% end %>

lists/app/views/lists/_search_results.html.erb
<% if results %>
  <p>&nbsp;</p>
  <p>&nbsp;</p>

  <h4>Results</h4>

  <p><%= format_search_query_text(query) %></p>

  <% if results.class == Hash %>
    <%= results[:error] %>
  <% elsif results.empty? %>
    There were no matches.
  <% else %>
    <% results.each do |task| %>
      <div><%= link_to task.name, task_path(task) %></div>
    <% end %>
  <% end %>
<% end %>

lists/app/views/lists/edit.html.erb
<%= render partial: "layouts/single_center_top" %>

  <h4>Edit List</h4>
  
  <%= render partial: "form", locals: {list: @list, create_or_update_text: @create_or_update_text} %>
  
  <p>&nbsp;</p>
  
  <%= link_to "Delete List", list_path(@list), method: "delete", data: {confirm: "Are you sure?"} %>
  
<%= render partial: "layouts/single_center_bottom" %>

lists/app/views/lists/index.html.erb
<%= render partial: "layouts/single_center_top" %>

  <h3>My Lists</h3>
  <p>&nbsp;</p>
  <% @lists.each do |list| %>
    <h4><%= link_to list.name, list_path(list) %></h4>
  <% end %>

<%= render partial: "layouts/single_center_bottom" %>

lists/app/views/lists/new.html.erb
<%= render partial: "layouts/single_center_top" %>

  <h4>Create List</h4>
 
  <%= render partial: "form", locals: {list: @list, create_or_update_text: @create_or_update_text} %>

<%= render partial: "layouts/single_center_bottom" %>

lists/app/views/lists/search.html.erb
<%= render partial: "layouts/single_center_top" %>

  <h3>Search</h3>

  <%= form_tag('/search', method: :post) do %>
    <%= hidden_field_tag "authenticity_token", form_authenticity_token %>
    <p>
      <%= label_tag "List (enter lists id or leave blank for any):" %><br>
      <%= text_field_tag "search[list_id]" %>
    </p>
    <p>
      <%= label_tag "Search term:" %><br>
      <%= text_field_tag "search[query]" %>
    </p>

    <%= submit_tag "Search" %>
  <% end %>

  <%= render partial: "search_results", locals: {results: @results, query: @query} %>

<%= render partial: "layouts/single_center_bottom" %>

lists/app/views/lists/show.html.erb
<%= render partial: "layouts/single_center_top" %>

<h2><%= @list.name %></h2>
<%= link_to "Edit", edit_list_path(@list) if authorize_resource(current_user,@list,:edit) %>
<p>&nbsp;</p>

<h5>Collaborators:</h5>
<p><%= @list.collaborators(true) %></p>


<p>&nbsp;</p>
<h4>Tasks:</h4>
<hr>

<% if @list.tasks.empty? %>
  There are no tasks in this list.  
<% end%>

<% @list.tasks.each do |task| %>
  <h5><%= link_to task.name, list_task_path(@list,task) %></h5>
  <p>Due: <%= task.format_due_date %></p>
  <p>Status: <%= task.status %></p>
  <hr>
<% end %>

<p>&nbsp;</p>
<p>&nbsp;</p>

<h5>Add Task</h5>
<%= render partial: "tasks/form", locals: {task: @task, list: @list} %>

<%= render partial: "layouts/single_center_bottom" %>